name: Terraform CI/CD

# Trigger on pushes to main, PRs, and manual dispatch if you add workflow_dispatch
on:
  push:
    branches:
      - feature/terraform-ci
  pull_request:
    types: [opened, synchronize, reopened]
  # workflow_dispatch:  # ← uncomment if you want a “Run workflow” button

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init -input=false
        # working-directory: infra      # ← commented out; run at repo root

      - name: Terraform Validate
        run: terraform validate
        # working-directory: infra      # ← commented out

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
        # working-directory: infra      # ← commented out

      - name: Upload Terraform plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan                # plan file is at the repo root now

  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Terraform plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: .                     # download plan into the repo root

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        # working-directory: infra      # ← commented out
