name: Terraform CI/CD

on:
  push:
    branches:
      - feature/terraform-ci
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init -input=false
        # working-directory: infra  # commented out because 'infra' folder isn't present

      - name: Terraform Validate
        run: terraform validate
        # working-directory: infra  # commented out due to missing infra directory

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
        # working-directory: infra  # commented out so plan runs at repo root

      - name: Upload Terraform plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan     # plan file lives at repo root now

  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Terraform plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          # path: infra   # commented out so artifact downloads to the repo root

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        # working-directory: infra  # commented out so apply runs at repo root
